# Generated by Django 6.0.2 on 2026-02-27 12:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UKRiskMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image_data', models.TextField(help_text='Base64-encoded PNG of UK risk map')),
                ('peak_risk', models.FloatField(blank=True, null=True)),
                ('peak_location_lat', models.FloatField(blank=True, null=True)),
                ('peak_location_lon', models.FloatField(blank=True, null=True)),
                ('grid_points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('forecast_date', models.DateField(help_text='The date this forecast is valid for')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('peak_risk', models.FloatField(blank=True, help_text='Peak risk % for the day', null=True)),
                ('recommendation', models.CharField(blank=True, help_text='GO / CAUTION / CANCEL', max_length=20)),
                ('peak_wind', models.FloatField(blank=True, help_text='Peak wind speed (m/s)', null=True)),
                ('peak_gust', models.FloatField(blank=True, help_text='Peak gust (m/s)', null=True)),
                ('peak_precip', models.FloatField(blank=True, help_text='Peak precipitation (mm/h)', null=True)),
                ('min_temp', models.FloatField(blank=True, help_text='Minimum temperature (°C)', null=True)),
                ('models_used', models.JSONField(default=list, help_text='List of weather model names used')),
                ('chart_image', models.TextField(blank=True, help_text='Base64-encoded forecast chart PNG')),
                ('text_report', models.TextField(blank=True, help_text='Generated text report')),
                ('thresholds_snapshot', models.JSONField(default=dict, help_text='Copy of threshold values used for this forecast run')),
                ('error_message', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='sites.site')),
            ],
            options={
                'ordering': ['-generated_at'],
                'unique_together': {('site', 'forecast_date', 'generated_at')},
            },
        ),
        migrations.CreateModel(
            name='HourlyForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('wind_speed', models.FloatField(help_text='Ensemble mean wind speed (m/s)')),
                ('wind_gusts', models.FloatField(help_text='Ensemble mean gusts (m/s)')),
                ('precipitation', models.FloatField(help_text='Ensemble mean precipitation (mm/h)')),
                ('temperature', models.FloatField(help_text='Ensemble mean temperature (°C)')),
                ('wind_spread', models.FloatField(default=0.0)),
                ('gust_spread', models.FloatField(default=0.0)),
                ('precip_spread', models.FloatField(default=0.0)),
                ('temp_spread', models.FloatField(default=0.0)),
                ('hourly_risk', models.FloatField(help_text='Risk score 0-100%')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_data', to='forecasts.forecastrun')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
